### ISSUE TITLE
Devnet-11 es-node cannot start after shutdown and restart

### ISSUE THREAD

**Issue by qizhou** [ethstorage/es-node#102]
Observed the following error message:

<img width="1335" alt="image" src="https://github.com/ethstorage/es-node/assets/2541286/5cae7632-2ec9-44ca-a5d5-2541d1523d55">

**Comment by qzhodl** [comment]
A workaround is to use `--download.start *latest block number* ` to ask the downloader to download blob from a specific block number. (you can get the latest block number by using http://65.108.236.27:5052/eth/v1/beacon/blocks/head)

**Comment by qizhou** [comment]
> A workaround is to use `--download.start *latest block number* ` to ask the downloader to download blob from a specific block number. (you can get the latest block number by using http://65.108.236.27:5052/eth/v1/beacon/blocks/head)

It works!
