### ISSUE TITLE
Need to check profit before submitting the mining proof

### ISSUE THREAD

**Issue by qzhodl** [ethstorage/es-node#139]
Use --miner.min-profit to specify the minimal profit that the miner needs to earn before submitting the mining transaction, and If the conditions are not met, we can drop the transaction directly? (since the tx will be invalidated in 64 epochs, and the profit during the time doesn't make much difference)

Since the smart contract doesn't have the miningReward() method yet, we may need to implement the same logic in Golang, and it should be straightforward. We'll use the method in the contract to get the value in the next devnet.

**Comment by syntrust** [comment]
Solved by https://github.com/ethstorage/es-node/pull/148
