### ISSUE TITLE
Stall filling

### ISSUE THREAD

**Issue by qizhou** [ethstorage/es-node#144]
Build info:
EthStorage node version v0.1.2-b8737930-1702090595
Build date: Tue 12 Dec 2023 04:20:27 AM EST
System version: amd64/linux
Golang version: go1.20

<img width="1985" alt="image" src="https://github.com/ethstorage/es-node/assets/2541286/669c8086-c408-435e-9185-51206f6e5468">

emptyToFile=16 while fillTasksRemain=0

**Comment by qzhodl** [comment]
The issue may due to this line: https://github.com/ethstorage/es-node/blob/ade821f68446d8e98890891ead94f55b417e0dac/ethstorage/p2p/protocol/syncclient.go#L830

**Comment by qizhou** [comment]
It is a race or what is the specific scenario?

**Comment by qzhodl** [comment]
Mingpeng was uploading BLOBs yesterday, so I guess the lastKvIndex may be greater than limit here: https://github.com/ethstorage/es-node/blob/ade821f68446d8e98890891ead94f55b417e0dac/ethstorage/p2p/protocol/syncclient.go#L1022
