### ISSUE TITLE
Replace snark.js with rapidsnark

### ISSUE THREAD

**Issue by qzhodl** [ethstorage/es-node#155]
# Rationale
Go-rapidsnark provides better performance (https://github.com/ethstorage/go-ethstorage/pull/14#issuecomment-1590816080), and our prover can go rid of the nodejs and snarkjs dependencies

**Comment by syntrust** [comment]
A quick test on MBP 2.9 GHz 6-Core Intel Core i9

snarkjs|go-rapidsnark|rapidsnark
-- | -- | --
43.8 | 47.1 | 8.2
60.1 | 82.3 | 16.7

**Comment by syntrust** [comment]
Test result with go-rapidsnark/prover@v0.0.11

platform|Proof for 2 samples (mode 2)| go version
-- | -- | -- 
MBP-AMD |26.8s | go1.22.3 darwin/amd64
AX-101| 15.6s |  go1.20.10 linux/amd64

Es-node is built from https://github.com/ethstorage/es-node/pull/281
