### ISSUE TITLE
EthStorage Docs

### ISSUE THREAD

**Issue by qzhodl** [ethstorage/es-node#16]
We may need to publish docs when the public testnet is out. A draft outline is here, need to fill the content
![image](https://github.com/ethstorage/es-node/assets/5291653/3143a9a2-2f76-43c0-864f-1af694a375d8)

**Comment by syntrust** [comment]
Can be reviewed here: https://app.gitbook.com/o/xslnT64ozeliMZwqZbdM/s/MYKgpUdEAwOLB9jkjh8m/overview/readme
or 
https://github.com/ethstorage/es-node-doc/pull/1
