### ISSUE TITLE
Needs a frontend/backend to do mainnet trust setup ceremony

### ISSUE THREAD

**Issue by qzhodl** [ethstorage/es-node#176]
# Rationale

Why should this feature exist?
Since we use zkSnark to do decode proof, we need a mainnet trust setup ceremony. We can investigate how 4844 do it and see if we can borrow the infrastructure.

**Comment by ping-ke** [comment]
Investigating using https://github.com/privacy-scaling-explorations/p0tion to trusted setup ceremony.
Current status:
1. Has follow https://p0tion.super.site/ to create github OAuth, Firebase service and functions
2. Set blob_poseidon circom ceremony and contribution

Problem: 
1. Github OAuth login does not save user info to firestore.
2. Ceremony set up with pot power = 22 will failed
3. Contribution would crash.

**Comment by ping-ke** [comment]
code and doc have been checked in to https://github.com/ethstorage/p0tion.
package publish to https://www.npmjs.com/package/@ethstorage-io/phase2cli.
UI deployed to https://ceremony.ethstorage.io/. 
maintain doc: https://docs.google.com/document/d/1WxZmFbFINaEdXk1Mjh58XsvWhJsl6VSsdfSBSj5sXz8/edit
related doc: https://github.com/ethstorage/p0tion/pull/5
