### ISSUE TITLE
Dashboard can be accessed on https://grafana.ethstorage.io

### ISSUE THREAD

**Issue by qzhodl** [ethstorage/es-node#196]
# Feature list
1. https
2. short URL
3. p2p network peer count & visual map to show the nodes location on the earth (optional)

# Implementation

Do you have ideas regarding the implementation of this feature?
Are you willing to implement this feature?

**Comment by ping-ke** [comment]
https://grafana.ethstorage.io/ has support HTTPS now, and it will redirect to ethstorage-monitoring-sepolia report.
