### ISSUE TITLE
Mining transaction failed because of "“block number too old”"

### ISSUE THREAD

**Issue by qzhodl** [ethstorage/es-node#210]
# Rationale

Why should this feature exist?
- real tx: https://sepolia.etherscan.io/tx/0x7b24a3c9349c774a88753596310e2f46408d60920ef5232cc1c3a09468dd3fe9
- Miners may want to get notified of this issue, shown on dashboard?
- Also what is the best strategy for miners when the reward is unknown (may be large) and the gas price is changing dramatically, e.g. set --miner.priority-gas-price to some specific value, or is there any better solution?
 
# Implementation

Do you have ideas regarding the implementation of this feature?
Are you willing to implement this feature?

**Comment by syntrust** [comment]
Closed because the probability this issue occurs should drop a lot due to the fix of https://github.com/ethstorage/es-node/pull/289 since the gas fee cap has been pumped to the max.
