### ISSUE TITLE
New API to support the OP Blob Archiver service to allow querying of all historical blobs from the beacon chain

### ISSUE THREAD

**Issue by qzhodl** [ethstorage/es-node#217]
# Rationale

Why should this feature exist?

OP uses an S3 [blob archiver](https://github.com/base-org/blob-archiver) to support querying all historical blobs from the beacon chain after the BLOB expires after 18 days, and EthStorage can also support the same interface so that OP can easily use EthStorage by configuring [beacon-archiver](https://docs.optimism.io/builders/node-operators/network-upgrades/ecotone#configure-a-blob-archiver-archive-nodes) without changing its code.

# Implementation

Do you have ideas regarding the implementation of this feature?
Are you willing to implement this feature?

**Comment by syntrust** [comment]
Implemented with https://github.com/ethstorage/es-node/pull/275
