### ISSUE TITLE
Could not start a downloader

### ISSUE THREAD

**Issue by espoir1989** [ethstorage/es-node#250]
Could not start a downloader"          err="missing trie node 768db6cc12749910458c9ce62981325da37317e07b49c25c88486976e86fd949 (path ) state 0x768db6cc12749910458c9ce62981325da37317e07b49c25c88486976e86fd949 is not available, not found

**Comment by qzhodl** [comment]
Please refer to this FAQ: https://docs.ethstorage.io/storage-provider-guide/storage-provider-faq#why-does-the-missing-trie-node-error-occur
