### ISSUE TITLE
tests: flaky TestSaveAndLoadSyncStatus

### ISSUE THREAD

**Issue by jhvst** [ethstorage/es-node#265]
While building the project with Nix, I received the following error:

```
error: builder for '/nix/store/yfhi5cfsg6dd0105rdavj9l9w8n2yzqg-es-node-0.1.12.drv' failed with exit code 1;
       last 10 log lines:
       > ok  	github.com/ethstorage/go-ethstorage/cmd/es-node	1.534s
       > ok  	github.com/ethstorage/go-ethstorage/cmd/es-utils/utils	1.540s
       > ok  	github.com/ethstorage/go-ethstorage/ethstorage	2.115s
       > ok  	github.com/ethstorage/go-ethstorage/ethstorage/miner	1.612s
       > ok  	github.com/ethstorage/go-ethstorage/ethstorage/node	2.118s
       > --- FAIL: TestSaveAndLoadSyncStatus (0.02s)
       >     sync_test.go:694: task 1 should be done.
       > FAIL
       > FAIL	github.com/ethstorage/go-ethstorage/ethstorage/p2p/protocol	92.320s
       > FAIL
       For full logs, run 'nix log /nix/store/yfhi5cfsg6dd0105rdavj9l9w8n2yzqg-es-node-0.1.12.drv'.
```

I did not catch up the error, since on rebuild everything worked again (this overwrites the so-called derivation log). It seems like this particular test, or the protocol tests which launch local nodes might be flaky.

Thought you might want to investigate.

**Comment by ping-ke** [comment]
I run the `go test .` under `ethstorage/p2p/protocol` folder, and all the tests pass, would you provide more info, like the go version, branch, commit hash, and so on.
![31d0ee338144710f8d9f2923a8db97c](https://github.com/user-attachments/assets/e2fe2889-0648-4cfc-8985-7dcc376e5bbb)

**Comment by jhvst** [comment]
I close this as stale, if I run into the problem again, I will post more debug information.
