### ISSUE TITLE
Integration test fail with error: failed to estimate gas: execution reverted: EthStorageContractL2: diff not match

### ISSUE THREAD

**Issue by ping-ke** [ethstorage/es-node#314]
#### System information

EthStorage node branch: integratiointest
System version: amd64/linux (88.99.30.186)
Golang version: e.g. go1.20
Integration test failed

#### Expected behavior
integration test can be passed successfully.

#### Actual behavior
The integration test failed with 91 submissions succeeding and one submission failing with “`failed to estimate gas: execution reverted: EthStorageContractL2: diff not match`"
![5452c7fccdae9b961f94b2ac215a395](https://github.com/user-attachments/assets/60cfea09-ba83-4ead-a41b-53bcffff7677)
![4faad26f4184f540b492c3870c83c7b](https://github.com/user-attachments/assets/6744ad11-6121-4f69-be78-e447f5778278)

#### Steps to reproduce the behavior
This issue just happened one time and does not happen again. You can run the integration test to try to reproduce it.
![1723368718475](https://github.com/user-attachments/assets/6049f2ee-8748-4449-b19e-c5c8ba2462de)

**Comment by syntrust** [comment]
Duplicated to https://github.com/ethstorage/es-node/issues/304
