### ISSUE TITLE
Devnet-1 Planning (Draft)

### ISSUE THREAD

**Issue by qizhou** [ethstorage/es-node#41]
A more realistic setup to mimic the ES testnet or mainnet environment.

- Base layer: devnet-9(or new)
- **Shard size: 1TB**
- RandomChecks: 2
- Nonce limit: 1024*1024
- Fill in about 1TB data (perhaps NFT images or Ethereum L2 data).
- Target proof submission interval: 10 mins (or 30 mins)
- Prepaid 1TB (or 512GB) fee?

Key results to figure out:
- Sampling time  (per block) ~ 6s (better if < 4s)
- Init time for 1TB
  - Filling ~ 8 hours (better if < 6 hours)
  - (After writing about 1TB) Syncing ~ 10 hours?
- Prove that storage providers can earn money!

**Comment by qzhodl** [comment]
We can close it since devnet-1 was closed
