### ISSUE TITLE
Support launching es-node with NO_ENCODE

### ISSUE THREAD

**Issue by qzhodl** [ethstorage/es-node#48]
Now run.sh only support creating storage file with ENCODE_BLOB_POSEIDON, and start es-node with mining enabled. We may want to support create storage file with NO_ENCODE, and start es-node without mining, so this data node can serve as a es_getBlob RPC node.

In our AX101 machine, A RPC request which did the decoding will cost ~50ms, and it will reduce to 10ms without the decoding operation. For a file with 28 chunks, it will have 50 * 28 = 1.4s latency, and the end user will feel more slow by adding some EVM latency. A NO_ENCODE es-node will provide better user experience.

**Comment by qzhodl** [comment]
@iteyelmp is deploying an es-geth and es-node with NO_ENCODE to test if the change fix the timeout issue.

**Comment by iteyelmp** [comment]
File size: **10.96MB**
Total chunk count: **91 (chunk size: 124kb)**


### No-Encode

'geth' — Time to get a chunk: **23-25 ms**

'geth' — Get **> 49 ** chunks: 
err= **out of gas**
_doCall_ execution time: **1977 ms**

'geth' — Get **48** chunks (5.81 MB):
_doCall_ execution time: **1524 ms**
‘node-js’ —  get file time: **17313 ms**



### Encode

'geth' — Time to get a chunk: **80-82 ms**

'geth' — Get > **21** chunks: 
err= **execution aborted (timeout = 5s)**
_doCall_ execution time: **2055 ms**

'geth' — Get **20** chunks (2.42 MB): 
_doCall_ execution time: **1828 ms**
‘node-js’ —  get file time: **8980 ms**

**Comment by iteyelmp** [comment]
Galileo Network

For the same file, the data size retrieved by **Galileo** network and **devnet** network **encode** mode is similar. **Galileo** alone takes less time than **devnet**.

File size: 10.96MB
Total chunk count: 24 (chunk size: 467.6kb)

Get > **5** chunks:
err= **out of gas**

Get **5** chunks (2.29 MB):
get file time: **5292 ms**

**Comment by qzhodl** [comment]
Since @iteyelmp tested the whole workflow successfully, I think we can close this issue
