### ISSUE TITLE
es-node version should print commit

### ISSUE THREAD

**Issue by qizhou** [ethstorage/es-node#54]
es-node should include commit hash or tag during compilation.

**Comment by qzhodl** [comment]
https://github.com/ethstorage/es-node/pull/67 did NOT update the document to use makefile, and we may also need to update the dockerfile?  @syntrust could you please update the related files.

**Comment by syntrust** [comment]
GUIDE.md is already updated in main branch.
Dockerfile is updated in https://github.com/ethstorage/es-node/pull/92
