### ISSUE TITLE
The time duration for p2p syncing is three times longer than filling empty when we a test 1T shard

### ISSUE THREAD

**Issue by qzhodl** [ethstorage/es-node#73]
The estimated time duration ratio of p2p syncing VS filling empty is around 2:1, so we may need to profile the process to see the root cause.

**Comment by qzhodl** [comment]
Filling empty time: 5 hrs
Sync time: 14 hrs
Peer count: 2 peers

**Comment by qzhodl** [comment]
@ping-ke could you please update your profiling data here?

**Comment by ping-ke** [comment]
![sync profile](https://github.com/ethstorage/es-node/assets/14110556/116d5534-0270-4a7a-8fd3-9c635f9c2b0f)
from the profile data, we can see most of the CPU is occupied by 3 functions marked in the image. 
- function 1 is used by prover.GetRoot in checkBlobCommit (used by the sync process) (41% CPU)
- function 2 is used by DecodeKV in the decodeKV (used by the sync process) (26% CPU)
- function 3 is used by TryEncodeKV in the CommitBlobs (used by the sync process and fill empty ) (28% CPU)

So, the CUP usage of the sync process is 3 times more to fill the empty process.
