### ISSUE TITLE
Unit test execution failed

### ISSUE THREAD

**Issue by iteyelmp** [ethstorage/es-node#76]
~~1. miner_test.go @syntrust~~
    It runs without any prompts and seems to be stuck.
<img width="202" alt="image" src="https://github.com/ethstorage/es-node/assets/6647261/a8e363e6-8eb2-4744-b443-e1893b956f27">

~~2. node_test.go @ping-ke~~ 
    panic: runtime error: invalid memory address or nil pointer dereference

~~3. node_mine_test.go @syntrust~~ 
    The test does not stop, CI needs to run a passed Test. The commit passed while reading the blob does not match.

~~4. sync_test.go @ping-ke~~ 
    task 1 should be done.

~~5. kzg_poseidon_prover_test.go @syntrust~~ 
    error = context canceled

~~6.  kzg_prover_test.go @syntrust~~ 
~~7. zk_prover_test.go @syntrust~~ 
   The contract address is wrong

~~8. signature_test.go @syntrust~~ 
    requested chainid 7011893061 does not match the configuration of the signer, wantErr false

9. ~~storage_manager_test.go @qzhodl~~
    ~~"../cmd/es-node/storage.dat" does not exist~~

**Comment by iteyelmp** [comment]
10. es-utils/utils_test.go @syntrust 
rpc error

11. es-node/utils_test.go @iteyelmp 
rpc error

**Comment by syntrust** [comment]
Since https://github.com/ethstorage/es-node/pull/78 merged, @iteyelmp you can merge the main branch to your branch to see if there are still UT failures.

**Comment by qzhodl** [comment]
We can close this issue since all the UT are checked in
