### ISSUE TITLE
Need to check if the user-passed storage.miner is a valid address

### ISSUE THREAD

**Issue by qzhodl** [ethstorage/es-node#80]
During the devnet-1 testing, a tester set his private key to --storage.miner flag, and es-node didn't report any error, used the last 20 bytes of the private as the miner address. At the end, the tester need to delete the whole data and re-sync again.

We need to validate the user-passed data and report error if it is the case.

**Comment by syntrust** [comment]
Fixed in https://github.com/ethstorage/es-node/pull/82
