### ISSUE TITLE
investigate performance loss on 7950X and 5975WX

### ISSUE THREAD

**Issue by qizhou** [ethstorage/es-node#85]
The filing performance on 7950X and TR 5975WX is much worse than ax101 (5950X).  Below are some numbers:

ax101:
<img width="1147" alt="image" src="https://github.com/ethstorage/es-node/assets/2541286/6a287930-ea40-4ba8-a5b5-ef8c4a442bd3">

~ 212 blobs/s

7950x:
<img width="1151" alt="image" src="https://github.com/ethstorage/es-node/assets/2541286/5f1420ee-827d-4306-9bdd-b90f78d9fd9b">

~ 36.0 blobs/s

<img width="1147" alt="image" src="https://github.com/ethstorage/es-node/assets/2541286/5841d64b-914f-420a-8ced-3611fbbc0d14">

~ 46 blobs/s

**Comment by qizhou** [comment]
Need to check whether it is CPU issue or networking

**Comment by qzhodl** [comment]
Should be fixed by https://github.com/ethstorage/es-node/pull/93
