### ISSUE TITLE
Using Infra free-tier as L1 source 

### ISSUE THREAD

**Issue by qizhou** [ethstorage/es-node#88]
Using infra as an L1 source can greatly save the cost (but sacrifice decentralized vs self-hosted node).  The main costs of es-node in JSON-RPC are
- call `GetKvMetas`
- call `lastKvIdx`
- notify new block and new BLOBs put event
- download BLOBs

For sync, the main cost is to call `GetKvMetas`, which returns the metadata of BLOBs.  Assuming its gas cost is 3000 (one SLOAD and others), one `GetKvMetas` can return 30,000,000 // 3000 = 10,000 BLOBs (other costs such as memory may apply).  Therefore, given 100,000 free calls per day, we can download 10,000 * 100,000 BLOB metadata, **which is ~119 TB** far exceeding the current shard size.

The rest calls are during the downloading stage, which depends on block generation and BLOBs put per block:
- for block generation, we have 3600 * 24 // 12 = 7200 blocks per day, which is quite small compared to 100,000
- for BLOBs event, it is a bit tricky, but we have at most 7200 * 6 BLOBs = 43,200, which is still in the range of 100,000.

As a summary, for EIP-4844,  Infra free tier as the L1 source may be sufficient to run an es-node.

**Comment by qzhodl** [comment]
Fixed by https://github.com/ethstorage/es-node/pull/93
