### ISSUE TITLE
"Minimum Hardware Requirements" in the guide needs to be updated

### ISSUE THREAD

**Issue by qzhodl** [ethstorage/es-node#91]
We may need to update the requirement here: https://github.com/ethstorage/es-node/blob/main/GUIDE.md#minimum-hardware-requirements 

CPU: at least 4 core 8 threads, otherwise the syncing process will be super long
Disk: needs to be NVMe disk to provide full sampling speed

**Comment by syntrust** [comment]
Solved in https://github.com/ethstorage/es-node/pull/92
