### ISSUE TITLE
Default sampling threads may be too small

### ISSUE THREAD

**Issue by qizhou** [ethstorage/es-node#96]
We use the number of CPUs as a number of sampling threads, which seems too small for synchronous IO sampling.  We should increase the value by 2x to make the sampling more efficient.

**Comment by qzhodl** [comment]
https://github.com/ethstorage/es-node/issues/81 is tracking this issue

**Comment by syntrust** [comment]
Doubled default threads in https://github.com/ethstorage/es-node/pull/98

On some machines, even x2 might not be sufficient, making it challenging to determine the optimal number of threads.
